apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jumpbox-cert
spec:
  commonName: jumpbox.k8s.lab.test
  dnsNames:
  - jumpbox.k8s.lab.test
  issuerRef:
    name: ca-issuer-selfsigned
    kind: Issuer
  secretName: jumpbox-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: contour
    projectcontour.io/websocket-routes: "/ws"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: jumpbox-ingress
spec:
## Comment next 4 lines if not using SSL certs
  tls:
  - secretName: jumpbox-tls
    hosts:
    - jumpbox.k8s.lab.test
  rules:
  - host: jumpbox.k8s.lab.test
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jumpbox-vmservice
            port:
              number: 80
