---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jumpbox-pvc
  namespace: demo1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: tanzu
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: jumpbox-configmap
    namespace: demo1
data:
  hostname: vmware-jumpbox
  public-keys: [[ YOUR ssh-rsa.pub ]]
  user-data: [[ YOUR BASE64 ENCODED CLOUD-INIT.YAML ]]
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm-selector: vmware-jumpbox
  name: vmware-jumpbox
  namespace: demo1
spec:
  imageName: vmi-e8e36255f6f2a48aa
  className: best-effort-xsmall
  powerState: poweredOn
  storageClass: tanzu
  advancedOptions:
    defaultVolumeProvisioningOptions:
      thinProvisioned: true
  volumes:
  - name: jumpbox-vol
    persistentVolumeClaim:
      claimName: jumpbox-pvc
  networkInterfaces:
  - networkType: vsphere-distributed
    networkName: wkld0
#  - networkType: nsx-t    
  readinessProbe:
    tcpSocket:
      port: 22
  vmMetadata:
    configMapName: jumpbox-configmap
    transport: CloudInit
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: jumpbox-vmservices
  namespace: demo1
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 7681
#  - name: ssh
#    port: 22
#    protocol: TCP
#    targetPort: 22
  selector:
    vm-selector: vmware-jumpbox
  type: LoadBalancer
